require('tables')

--For buffs id you can check the buffs.lua in resources
whitelist = {
    Player_1 = { -- player name
        WAR = L{}, -- buffs id separated by coma WAR = L{40, 41}, this will show only the protect and shell buffs on Warrior main job 
        MNK = L{},
        WHM = L{},
        BLM = L{},
        RDM = L{},
        THF = L{},
        PLD = L{},
        DRK = L{},
        BST = L{},
        BRD = L{},
        RNG = L{},
        SAM = L{},
        NIN = L{},
        DRG = L{},
        SMN = L{},
        BLU = L{},
        COR = L{},
        PUP = L{},
        DNC = L{},
        SCH = L{},
        GEO = L{},
        RUN = L{},
    },
    Player_2 = { -- player name
        WAR = L{}, -- buffs id separated by coma WAR = L{40, 41}, this will show only the protect and shell buffs on Warrior main job
        MNK = L{},
        WHM = L{},
        BLM = L{},
        RDM = L{},
        THF = L{},
        PLD = L{},
        DRK = L{},
        BST = L{},
        BRD = L{},
        RNG = L{},
        SAM = L{},
        NIN = L{},
        DRG = L{},
        SMN = L{},
        BLU = L{},
        COR = L{},
        PUP = L{},
        DNC = L{},
        SCH = L{},
        GEO = L{},
        RUN = L{},
    },
}

blacklist = {
    Player_1 = { -- player name
        WAR = L{}, -- buffs id separated by coma WAR = {40, 41}, this will filter only the protect and shell buffs on Warrior main job
        MNK = L{},
        WHM = L{},
        BLM = L{},
        RDM = L{},
        THF = L{},
        PLD = L{},
        DRK = L{},
        BST = L{},
        BRD = L{},
        RNG = L{},
        SAM = L{},
        NIN = L{},
        DRG = L{},
        SMN = L{},
        BLU = L{},
        COR = L{},
        PUP = L{},
        DNC = L{},
        SCH = L{},
        GEO = L{},
        RUN = L{},
    },
    Player_2 = { -- player name
        WAR = L{}, -- buffs id separated by coma WAR = {40, 41}, this will filter only the protect and shell buffs on Warrior main job
        MNK = L{},
        WHM = L{},
        BLM = L{},
        RDM = L{},
        THF = L{},
        PLD = L{},
        DRK = L{},
        BST = L{},
        BRD = L{},
        RNG = L{},
        SAM = L{},
        NIN = L{},
        DRG = L{},
        SMN = L{},
        BLU = L{},
        COR = L{},
        PUP = L{},
        DNC = L{},
        SCH = L{},
        GEO = L{},
        RUN = L{},
    },
}
